tasks:
  - name: date
    key: d
    cmd: date

  - name: date w. confirm
    key: D
    cmd: date
    confirm: true
    clear: true

  - name: fzf (intentionally very long task name)
    key: f
    cmd: fzf --preview "bat {}"

  - name: fail
    key: F
    cmd: "false"

  - name: find/src
    key: S
    cmd: find .
    working_dir: src/
    confirm: true

  - name: sleep
    key: s
    cmd: sleep 100

  - name: cargo install
    key: I
    cmd: cargo install --path=.

  - name: vim
    key: v
    cmd: nvim

  - name: not-existent
    key: n
    cmd: foobar --hello
    clear: true

  - name: echo env var
    key: e
    env:
      SOME_KEY: "some value"
    cmd: echo "The value of SOME_KEY is '$SOME_KEY'"
